News-article-Ground-to-cloud-III-webinar
arup-group/giraphe-news pull request #6
Opened 2023-11-14 11:23 UTC by elizabethcbailey

includes also images.

2023-11-14 20:45 UTC, juliaklusek requested changes
Can the folder name start with lower case for consistency?
A big banner is missing for the new article. It's important that each folder has all five files - if one of them is missing we will get errors on the page.

2023-11-14 20:45 UTC, juliaklusek commented on news/Ground-to-cloud/details.md
> +You will also learn about recent advancements and updates in OpenGround that empower you to extract maximum value from the platform.This webinar is the perfect opportunity to stay at the forefront of
There's a space missing after "platform." :)

2023-11-14 20:45 UTC, juliaklusek commented on news/Ground-to-cloud/metadata.json
> +    "created": "2023-09-14"
I want to make sure this line and the article is supposed to say September and not November. We want it to appear as if we published the article 2 months ago?

2023-11-14 20:45 UTC, juliaklusek commented on news/Ground-to-cloud/smallImage.svg
Do we want it to appear on the news card on the main news page? The image should be 160x160

2023-11-15 16:19 UTC, elizabethcbailey commented on news/Ground-to-cloud/details.md
> +You will also learn about recent advancements and updates in OpenGround that empower you to extract maximum value from the platform.This webinar is the perfect opportunity to stay at the forefront of
```suggestion
You will also learn about recent advancements and updates in OpenGround that empower you to extract maximum value from the platform. This webinar is the perfect opportunity to stay at the forefront of geotechnical software technology. Whether you’re considering a migration to OpenGround or are already a user, you’ll find valuable information to enhance your geotechnical data workflows.  
```

2023-11-15 16:21 UTC, elizabethcbailey commented on news/Ground-to-cloud/metadata.json
> +    "created": "2023-09-14"
Yes that is correct. This will be the only time that happens. We want it to be in line with when the webinar actually happened and to appear before the other webinar for example. Moving forward we will just publish articles with a more recent date.

2023-11-15 16:21 UTC, elizabethcbailey commented on news/Ground-to-cloud/metadata.json
> +    "subTitle": "conference",
```suggestion
    "subTitle": "webinar",
```

2023-11-15 16:28 UTC, elizabethcbailey commented on news/Ground-to-cloud/metadata.json
> +    "created": "2023-09-14"
Also, I tried three times to get the folder to have lower case g but it seems to not have accepted it.

2023-11-15 16:29 UTC, elizabethcbailey commented on news/Ground-to-cloud/smallImage.svg
nope that is a mistake! will correct.

2023-11-15 16:44 UTC, juliaklusek approved these changes

2023-11-15 16:44 UTC, merged